# * of *

import occ

coding = "v2.0"

coder = occ.Coder()
coder.loadPreviouslyCoded(coding)#, N=1, rand=False)

import re

for x in coder.obituaries:
    roles = ["innovator", "expert"]
    filler = ["in", "on", "of"]
    exp = "(?:%s) (%s) (.{0,50})" % ( "|".join(roles), "|".join(filler) )

    find_them = re.findall(exp, x['fullBody'])

    for y in find_them:
        print(y)

"""('on', 'statistics on religious groups, died Tuesday at Ne')
('on', "solar heating, publishing books including ''Solar ")
('on', 'dolphin intelligence at the New York Aquarium in B')
('in', 'the economic and financial section at the League o')
('on', 'historic religious apparitions; and an investigato')
('on', 'contract law who was co-author of a primary textbo')
('on', 'the assessment of vaccines.')
('on', 'marine mining, died last Saturday at his home in A')
('on', 'city planning who specialized in designs for the t')
('of', 'combining orchestra with the accordion-laced conju')
('on', 'agribusiness and business ethics, died on Sunday a')
('on', "Russian literature, joined Queens College's facult")
('in', "the 1960s and '70s who pushed dance into the 20th ")
('in', 'dental research and radiography, died yesterday at')
('in', 'the use of imaging radar to produce an image of th')
('on', 'coins, currencies and medals, died of an embolism ')
('on', 'the Shaker religious sect, died on Tuesday at Sama')
('on', 'constitutional, administrative and labor law, died')
('on', 'municipal hospitals, serving on a task force creat')
('in', 'the history of small boats, Mr. Gardner built a co')
('on', 'the stylish life well known for his writing, cooki')
('on', 'industrial policy and European unity. In 1951, Chu')
('on', 'the effects of noise in the workplace whose work h')
('in', 'European cuisine and played the zither and organ.')
('on', 'diseases of aquatic creatures, died of complicatio')
('in', 'psychosomatic medicine, died on Jan. 30 at a nursi')
('in', 'couture shoe design, died on Friday at Southampton')
('on', 'skin pigmentation disorders who trained in both ch')
('in', 'head injuries, died Saturday at the U.S. Naval Hos')
('in', 'the biochemistry of sleep. With Prof. John Pappenh')
('in', 'labor law and a former chief counsel of the Nation')
('in', 'the workings of government. A familiar figure at g')
('on', 'refugee and humanitarian issues and international ')
('on', 'Asian human rights, routinely testifying before Co')
('in', 'direct-response advertising and a managing directo')
('on', 'the United Nations and its specialized agencies, b')
('in', 'cell biology and a neurobiologist at Cornell, cont')
('on', 'leprosy, died of heart failure Monday in Atlanta, ')
('in', 'weapons proliferation, died on Jan. 7 at Brookhave')
('in', "Tito's Communist Yugoslavia who defected in 1961 t")
('on', 'naval logistics who wrote about the dangers of the')
('in', 'sabotage and escape and evasion, they specialized ')
('in', 'glazes, finishes and the restoration of wallpaper,')
('on', 'conflict resolution and mediation.')
('in', 'racial and ethnic politics in Los Angeles and the ')
('on', 'strictly Orthodox Judaism, told the Israel radio. ')
('on', 'Hebrew who helped prove the antiquity of the Dead ')
('of', 'animation who teamed with William Hanna to give ge')
('on', 'the Russian theater (his book "Moscow Rehearsals" ')
('in', 'recycling newsprint, died on July 11 at his home i')
('on', 'archery and on the design of bows and arrows, and ')
('on', 'hospital and school planning, he lectured at many ')
('on', 'the event and, eventually, the curator of the Sixt')
('on', 'Hawthorne, Poe and Whitman, and chairman of Hofstr')
('in', "the early development of submarines in the 1920's ")
('on', 'how to tell whether a stamp was genuine. He wrote ')
('on', 'welfare and relations between state and federal go')
('on', 'the Mesolithic period, "helped to develop European')
('on', 'the administration of criminal justice and on the ')
('on', 'the German existentialist philosopher Martin Heide')
('on', "public health who was noted for ''his innovative, ")
('in', 'public finance, especially as it pertains to state')
('on', 'espionage.')
('in', 'trusts and estates.')
('on', 'antitrust matters as well as on international comm')
('on', 'the literature of the Renaissance in England and I')
('in', 'reactor safety who retired from the Brookhaven Nat')
('on', 'the English poet William Cowper. In addition to wr')
('of', 'the Natural History Museum in London and serving i')
('on', 'potatoes, died on Feb. 4 at a nursing home in Itha')
('in', 'penal reforms, died Thursday at Spohn Hospital in ')
('in', 'the staging of ballets from the 20th-century Russi')
('in', 'stage lighting, died on Wednesday at a hospital in')
('on', 'tax law and corporate reorganization, died last Su')
('on', 'Russian literature, Dr. Winner was 86.')
('on', 'Chekhov, he shifted his focus to linguistics and s')
('on', 'the history of medicine, died July 3 at his home i')
('in', 'community relations who was the staff director of ')
('in', 'psychoanalytic theory and practice and the neuroph')
('in', 'the field of developmental disabilities, died on N')
('on', 'cancer surgery, died on Jan. 17 at his home in Ten')
('on', '19th-century literature, had never heard of Dougla')
('on', 'Chinese military affairs, died March 27 in Newport')
('on', 'the stock market, was interviewed for articles in ')
('on', 'the diagnosis and treatment of kidney disease in c')
('on', 'natural resources and an economist who advised two')
('on', 'architecture and a gourmet cook," Mr. Forbes said.')
('on', 'antipoverty issues, worked in community developmen')
('on', "pursuit and interceptor aircraft in the 1930's, se")
('in', "the study of what are called ''folded'' mountain r")
('on', 'Milton and a noted educational theorist who taught')
('in', 'other card games as well as in backgammon. He wrot')
('on', 'vital statistics, he began his Government career i')
('on', 'organized crime and oversaw investigations of some')
('on', 'brainwashing who testified in several high-profile')
('on', 'mind control. In the following years, she repeated')
('in', 'the fields of philosophy, science, anthropology an')
('on', 'the writings and theories of Einstein and the phil')
('on', 'gemstones and a prominent figure in the diamond in')
('on', 'the analysis of public policy and government budge')
('on', 'the Federal courts and constitutional law, died ye')
('on', 'ancient languages, died on March 30 at his home in')
('on', 'food and wine died Saturday at her rural English h')
('on', 'pregnancy-associated breast cancer and the causes ')
('on', 'everything under the sun influenced two generation')
('in', 'the archdiocesan matrimonial court.')
('on', 'Asian art who as director of the Cleveland Museum ')
('on', 'public-utility rates and was an advocate of low ra')
('on', 'the Renaissance and the Reformation, was an author')
('in', 'the fields of transportation, water resources, eco')
('on', 'religious conservatives.')
('in', 'soil engineering, the branch of civil engineering ')
('in', 'respiratory medicine at the University of Pennsylv')
('in', 'submarine warfare and an able administrator.')
('on', 'ice dancing and champion figure skating, she wrote')
('on', 'Social Security and served as chairman of the Hous')
('in', 'foreign affairs and social policy, died on Sunday ')
('on', 'the Soviet bloc, led fact-finding missions through')
('in', 'Belgian-American legal affairs, Mr. Bachrach was t')
('on', 'banking law, died on Sunday at Martin Memorial Hos')
('on', 'Czechoslovakia who aided and encouraged dissidents')
('in', 'infectious diseases who helped develop antibiotics')
('in', "this subject.''")
('on', 'medieval social history, died on June 7 at his hom')
('on', 'alternatives to the courts for resolving disputes,')
('in', 'the interior design of corporate offices and hotel')
('on', 'China and the Far East, Mr. Barnett retired from t')
('on', 'arborviruses, coupled with earlier suspicious deat')
('on', 'press matters, died on Saturday in a residence for')
('on', 'education in the health sciences, died on Nov. 14 ')
('in', 'progressive rock since his days with the Mothers o')
('on', 'the structure of high-rise buildings. He helped de')
('in', 'the consulting world," said James H. Kennedy, publ')
('on', 'business cycles who for decades traced the history')
('in', 'biostatistics at the Fox Chase Cancer Center in Ph')
('in', 'the use of lasers in cancer surgery, a specialty h')
('on', 'minority police officers and their sometimes troub')
('on', 'the subject, died on Saturday at Stonewall Jackson')
('on', 'propaganda and took a leave from Washington and Le')
('on', 'Middle Eastern affairs, has died, state news agenc')
('on', 'arbovirology, the study of insect-borne viral dise')
('on', 'training hunting dogs, died on Saturday after he l')
('on', 'trauma who carried out path-breaking research, hel')
('on', 'the Reformation, died Friday at Stanford Hospital ')
('on', 'economic development who was a former director of ')
('on', 'radar and human survival in space, and an industri')
('on', 'life-support systems for space vehicles. He also w')
('in', "women's health care, died Nov. 9 at her home in Te")
('in', 'an exotic or unlikely field of endeavor by an ofte')
('on', 'early childhood education and a champion of giving')
('on', 'marketing, died on Thursday at the Hudson Valley H')
('on', 'biliary tract surgery, he wrote numerous articles ')
('on', 'the Weimar Republic, which he analyzed in his book')
('in', 'the field of preventive medicine and through how-t')
('in', 'the new field of radio.')
('on', 'Asia, expressed a widely held view in 1983 when he')
('in', 'strategic nuclear doctrine who advised Democratic ')
('on', 'national security, were awarded the Medal of Freed')
('on', 'the bomb. A few minutes into the flight, he replac')
('in', 'all kinds of human transplants. For 23 years, he w')
('in', "rheumatology, died on Feb. 17 at St. Vincent's Hos")
('on', 'Raphael as well as on Italian Mannerism, the highl')
('on', 'the Soviet Union concluded when Dr. Sakharov began')
('in', 'Greek tombstones and Attic pottery, Mr. Frel worke')
('on', 'the Mafia, compared Mr. Rizzuto to Mr. Gotti, the ')
('in', 'child development, died on Tuesday at her home in ')
('of', 'the jazz trumpet, died yesterday afternoon at the ')
('in', 'explosive and solid rocketry, he assisted in the c')
('in', 'public finance, died on Thursday in a Philadelphia')
('in', 'her field. From then on, she exhibited widely, in ')
('in', 'the study of the nuclear reactions that took place')
('on', 'the evolution of mammals, died on Nov. 8 at Presby')
('on', 'special education and mental disabilities and prof')
('on', 'the Soviet Union, recalled using one of Dr. Schuma')
('on', 'what happens in the brain as it ages and on Alzhei')
('in', 'publishing books about contemporary young musician')
('in', 'Broadway musicals, died yesterday at his home in M')
('on', 'war crimes, and Jennifer Dworkin, a philosopher an')
('on', 'the Middle East and Cyprus, died on Sunday at his ')
('on', 'the disease. Patients fare best, he believed, when')
('on', 'labor economics who had been the dean and a profes')
('on', 'national and New York housing policy who was chair')
('on', "Indochina, said Dr. Kahin's view of Washington's V")
('in', 'international banking, served in a key liaison rol')
('on', 'student unrest and police-community relations, die')
('in', 'industry trade shows and a major donor to his alma')
('on', 'King John of England, the widely opposed ruler who')
('on', "radio history, said in an interview on Thursday. '")
('on', 'depression who was a former chief of the Federal m')
('on', 'space exploration, deep sea mining and the use of ')
('on', 'how people think. He earned an international reput')
('on', 'tax law who served as an Assistant Treasury Secret')
('on', 'development and education. In the late 1950s, afte')
('on', 'nuclear arms control, died on Monday at Stanford H')
('on', 'beekeeping techniques, Mr. Mraz lectured and consu')
('on', 'the law of evidence and served as chairman of the ')
('in', 'radio systems design, died Sunday at the Kensingto')
('in', 'the world energy markets, died on Jan. 13 in his h')
('in', 'lighting, he worked mostly, though not entirely, i')
('on', 'municipal bonds, died Saturday at the Columbia-Pre')
('on', 'cultural development in India and Southeast Asia, ')
('on', 'the social and economic consequences of earthquake')
('on', 'preventing earthquake damage and wrote extensively')
('on', 'Shakespeare, wrote that Professor Muir was "recogn')
('on', 'earthquakes. He once gave two astronauts, Capt. Al')
('in', 'the State Department. As a Foreign Service officer')
('on', "organized crime, once called ''a familiarity with ")
('on', 'the civil rights movement and a professor emeritus')
('on', 'the formation of stars, died on Jan. 7 in Esslinge')
('on', 'the wine-making business. In 1974 he was the host ')
('on', 'Ugaritic literature - texts written in an extinct ')
('on', "the city's government, died of respiratory failure")
('on', 'thunderstorms.')
('in', 'the talent agency that managed the budding careers')
('on', 'economic development who was a former director of ')
('on', 'the workings of charitable foundations who wrote e')
('on', 'Africa, and, as the president of the African-Ameri')
('on', 'modern Germany, died on Sunday in the Lake County ')
('on', 'grief in children and a child psychoanalyst who he')
('on', 'glaucoma who practiced ophthalmology in Manhattan ')
('on', 'Africa and Gabon at the Institut de Relations Inte')
('of', 'the board and one of the best mediator-arbitrators')
('on', 'determining how fully arms control treaties were c')
('on', 'arms control treaties, said of Mr. Katz: "In the 1')
('on', 'the use of photographic systems in piercing cold-w')
('in', 'German Expressionism, exposed him to that school o')
('in', 'finance for agriculture and food companies in deve')
('on', "the Balkans. ''Even in Serbia, there will be few p")
('on', 'consumer problems and was executive director of th')
('in', 'banking, joined the First National Bank as a telle')
('on', 'reptiles and amphibians and curator emeritus of th')
('on', 'Jewish dance history, said that Ms. Levi-Tanai had')
('on', 'economic matters.')
('in', 'amphibious warfare. He taught courses in his speci')
('on', 'arthritis, joined the National Foundation for Infa')
('on', 'raising orchids. They hired him as a technical con')
('on', 'Japan, died on March 17 at his home in Washington.')
('in', 'stress engineering.')
('in', 'statistical applications for biological and medica')
('on', 'rabies and arthropod-borne viral diseases who was ')
('in', 'the public domain dated to the days of Judge Samue')
('in', 'medieval and modern Spanish literature, Dr. Willis')
('on', 'corporate taxation who helped build Coltec Industr')
('on', 'solid-state materials and a professor of physics, ')
('on', 'neurological disorders who spearheaded a landmark ')
('in', 'retirement benefits who was president of the Serge')
('on', 'the coffee trade. He officially retired in 1974, b')
('in', 'his art form, died on Tuesday in Damascus, Syria. ')
('on', 'sharks, died on Wednesday at her home in Sarasota,')
('in', 'what is known as total parenteral nutrition: whole')
('in', 'plant diseases, Elvin C. Stakman, who encouraged h')
('in', "the field of artists' materials and techniques, wh")
('in', 'community mental health programs and an adviser on')
('on', 'blindness, died on Thursday at Beth Israel Medical')
('on', 'gynecological cancer. He also did original work in')
('on', 'the history of Chinese immigration to the United S')
('in', 'the Government of Prime Minister Jawaharlal Nehru.')
('in', 'fencing and horsemanship but who won stardom with ')
('on', 'reading disabilities, Isabelle Liberman died in 19')
('on', 'bioterrorism. In 1998 he was a founding director o')
('on', 'the American Shakers, died on Saturday at the Gree')
('on', 'sickle cell anemia who helped establish broader fe')
('in', 'the chemistry of neurotransmitters, was noted for ')
('on', "cosmetic chemistry, developed some of his company'")
('on', 'Handel, died on Sunday at Princeton Medical Center')
('in', 'fluorine chemistry who worked on the team that bui')
('in', 'adolescent psychiatry and a former chief of psychi')
('on', 'United States foreign policy toward Africa, died o')
('on', 'children came under a cloud when her daughter Caro')
('on', 'German imperialism, he rejected the argument that ')
('in', 'the field, said in an interview on Wednesday.')
('on', 'Eastern Europe, wrote in a 1969 book that Mr. Peli')
('on', 'Shakespeare whose theories influenced some of the ')
('on', 'aggression and terrorism, died last Friday in Main')
('in', 'the murders of the actress Sharon Tate and several')
('on', 'Asia for government, news and non-profit organizat')
('in', 'languages, died last Friday in Bergen Pines Hospit')
('in', 'the design of church furnishings.')
('in', 'Chinese and Japanese religions, taught at Columbia')
('in', 'the end game.')
('on', 'population trends and the demographic statistics t')
('in', 'African-American literature at Duke University, sa')
('on', 'the brain functions linked to emotions and social ')
('on', 'the literature of the Beat Generation as well as a')
('on', 'international taxation, trade and economics who ad')
('in', 'dyslexia who frequently consulted with public and ')
('in', 'labor law and served several years as chairman of ')
('in', 'occupational medicine. Until he retired in 1974, h')
('in', 'optics, he developed several variants of polarized')
('on', 'industrial relations and a former dean of the Ford')
('in', 'refugee law and over the years helped thousands of')
('on', 'embryology and cell biology, died yesterday a t hi')
('on', 'addiction. In New York City in 1959, she became ch')
('on', 'the relationship between church and state, joined ')
('in', 'international development policy, was director of ')
('on', 'the flora and ecology of South and Central America')
('in', 'the field of crooked gambling. During his Army ser')
('in', 'health-care law, died Friday of a heart attack at ')
('in', 'the Pentagon and in 1962 he was the Controller of ')
('on', 'Portuguese-speaking countries at the Council on Fo')
('on', 'what was highbrow, what was lowbrow and what was n')
('on', 'corn genetics, died Wednesday at a nursing home in')
('on', 'Impressionist art and a directorship of the auctio')
('in', 'the transmission of electricity.')
('on', 'Vietnamese literature, argued in a 1972 publicatio')
('on', 'legal ethics, died of a heart attack Saturday at h')
('on', 'Beowulf, the longest poem surviving in Old English')
('on', 'ancient Micronesian navigation methods, set about ')
('on', 'alcoholism and a leader in the effort to classify ')
('on', 'the fluctuations of stock prices, died on Monday a')
('on', 'psychosomatic illness, died on Saturday at St. Luk')
('in', 'public health policy who became a professor at the')
('on', 'mental health policy that in 1968, he moved to the')
('in', 'the metallurgy involved in extracting copper, lead')
('in', 'labor law, Mr. Isaacson served in both the public ')
('on', 'lower back pain, Dr. Jacobs was for 31 years an at')
('on', 'Ottoman Turkish music, told a reporter for The New')
('in', 'renal biochemistry and a specialist in gerontology')
('on', 'Russia and Ukraine and a vice president of the Nat')
('on', 'the Cold War and a program director at the Davis C')
('on', 'the psychology of people who choose religious voca')
('on', 'Soviet politics.')
('on', 'Oriental porcelains and bronzes, died Saturday of ')
('on', 'arms and armor at the Metropolitan Museum of Art, ')
('in', 'the arcane world of medieval Islamic law, died on ')
('on', 'lilies, died of a brain tumor Aug. 23 at the Presb')
('on', 'welfare legislation. He pushed through creation of')
('on', 'the use of force by the police, and the top traini')
('on', 'police practices and a co-author with Dr. Fyfe of ')
('in', 'trademark law.')
('on', 'animal behavior who coached the cast; and the pupp')
('on', 'diseases of the pancreas, died of cancer yesterday')
('in', 'the field although his formal education did not go')
('in', 'the arcane world of medieval Islamic law, died on ')
('on', 'international organizations. He retired in 1971 as')
('on', 'the psychology of television and its impact on chi')
('in', 'designing museum displays of non-Western art, died')
('in', 'infectious diseases whose research contributed to ')
('in', 'small arms, he collected 18 tons of German weapons')
('on', 'bats and a former curator at the American Museum o')
('on', 'bats who is the director of the North American Sym')
('in', 'antisubmarine warfare who had been director of sci')
('on', 'polar ice, died last Friday. He was 62 years old a')
('on', 'sea-ice dynamics and remote sensing, he lectured a')
('on', 'climate for the National Oceanic and Atmospheric A')
('in', 'loyalty matters, was retained by the Board of High')
('on', 'antique clocks, and collected them with such a dis')
('on', 'Asia, to Philip Jaffe, the editor of Amerasia, whi')
('on', 'East Asia and served as Ambassador to Indonesia du')
('on', 'the history of black Americans, died Dec. 20 at hi')
('on', 'Eastern Europe. He served as Assistant Secretary o')
('on', 'taxation and public finance, died Sunday at Beth I')
('on', 'United States coins. He helped found the Early Ame')
('on', 'German culture in the Moscow literary world, writi')
('on', 'international trade and advised Congress and the U')
('in', 'that field, died on Sunday at his home in Hampton ')
('on', 'European affairs. He then moved back to the State ')
('in', 'the field, lecturing and writing numerous articles')
('in', 'international investments, especially in Europe.')
('in', 'the intricacies of nuclear weaponry, as well as a ')"""